{% set name = "act-atmos" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0794f22a442136640ac862a607ba0c07886c325aad48dae6fd795c561d13c4f2

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyproj >=2.3.1
    - pandas
    - xarray
    - matplotlib-base
    - numpy
    - scipy
    - astral
    - dask
    - distributed
    - pint
    - cartopy
    - metpy
    - boto3
    - netcdf4
    - requests

test:
  requires:
    - pytest
  imports:
    - act
  commands:
    - py.test --pyargs act

about:
  home: https://github.com/ARM-DOE/ACT
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Python library for working with atmospheric time-series by n-dimension datasets'

  description: |
    Toolkit for working with atmospheric data in every aspect
    of the scientific process.  From discovery and downloading,
    to visualization, to retrievals and advanced calculations
  doc_url: https://arm-doe.github.io/ACT/
  dev_url: https://arm-doe.github.io/ACT/

extra:
  recipe-maintainers:
    - AdamTheisen
    - rcjackson
    - zssherman
