{% set name = "act-atmos" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 429678c1b68e588711c594965a6c04fef62f04c3b8235f0308c1edc5c035ea22

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyproj >=2.3.1
    - pandas
    - xarray
    - matplotlib-base <=3.2.2
    - numpy
    - scipy
    - dask
    - distributed
    - pint
    - cartopy <=0.17.0
    - metpy
    - boto3
    - netcdf4
    - six
    - requests
    - arm_pyart
    - skyfield

test:
  requires:
    - pytest
  imports:
    - act
  commands:
    - py.test --pyargs act

about:
  home: https://github.com/ARM-DOE/ACT
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python library for working with atmospheric time-series by n-dimension datasets

  description: |
    The Atmospheric data Community Toolkit (ACT) is an open source Python toolkit for working 
    with atmospheric time-series datasets of varying dimensions. The toolkit is meant to have 
    functions for every part of the scientific process; discovery, IO, quality control, 
    corrections, retrievals, visualization, and analysis. It is meant to be a community platform 
    for sharing code with the goal of reducing duplication of effort and better connecting the 
    science community with programs such as the Atmospheric Radiation Measurement (ARM) User Facility.
  doc_url: https://arm-doe.github.io/ACT/
  dev_url: https://github.com/ARM-DOE/ACT

extra:
  recipe-maintainers:
    - AdamTheisen
    - rcjackson
    - zssherman
    - jhemedin
