{% set name = "act-atmos" %}
{% set version = "2.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3300ca4faa3abe8be05426a67af8449d7e4f9913dbbfc92b94d623e185058c3c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.9
    - pyproj
    - sgp4 >=2.23
    - pandas
    - xarray
    - matplotlib-base
    - numpy
    - scipy
    - dask
    - pint
    - metpy
    - netcdf4
    - six
    - lxml
    - requests
    - skyfield
    - python-dateutil
    - pytz
    - lazy_loader
    - fsspec
    - cmweather
    - arm-test-data
    - aiohttp

test:
  imports:
    - act.io
    - act.discovery
    - act.plotting
    - act.qc

about:
  home: https://github.com/ARM-DOE/ACT
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python library for working with atmospheric time-series by n-dimension datasets
  description: |
    The Atmospheric data Community Toolkit (ACT) is an open source Python toolkit for working 
    with atmospheric time-series datasets of varying dimensions. The toolkit is meant to have 
    functions for every part of the scientific process; discovery, IO, quality control, 
    corrections, retrievals, visualization, and analysis. It is meant to be a community platform 
    for sharing code with the goal of reducing duplication of effort and better connecting the 
    science community with programs such as the Atmospheric Radiation Measurement (ARM) User Facility.
  doc_url: https://arm-doe.github.io/ACT/
  dev_url: https://github.com/ARM-DOE/ACT

extra:
  recipe-maintainers:
    - AdamTheisen
    - rcjackson
    - zssherman
    - mgrover1
